stages:
  - build
  - deploy

variables:
  MIX_DEPS: deps

build:
  stage: build
  image: appuio/shop-example-users-builder
  script:
    # install necessary application packages
    - mix deps.get
    # build the application sources
    - mix release
  cache:
    key: $CI_PROJECT_ID
    paths:
      - $MIX_DEPS
  artifacts:
    expire_in: 5min
    paths:
      - _build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls
    - docker -v 
  tags:
    - dockerbuild