stages:
  - build
  - deploy

build:
  stage: build
  image: appuio/shop-example-users-builder
  script:
    - ls

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker -v 
  tags:
    - dockerbuild