version: "2.1"
services:
  users:
    # build: ../users-builder
    image: appuio/shop-example-users-builder
    command: /bin/sh -c "mix deps.get;mix ecto.migrate;mix phoenix.server"
    environment:
      DB_USERNAME: users
      DB_PASSWORD: secret
      DB_DATABASE: users
      DB_HOSTNAME: users-db
      MIX_ENV: dev
      SECRET_KEY: "l1jp*8SggVjlWpGI5QkFG3UUB&ob@lY@s4v^h83&Rv7YjI4yD8FqENTr^6ju40Cz"
    ports:
      - "4000:4000"
    volumes:
      - /opt/git/services/users:/app/source

  users-db:
    extends:
      file: docker-compose.yml
      service: users-db
