version: "2.1"
services:
  users:
    build: .
    environment:
      DB_HOSTNAME: users-db
      DB_USERNAME: users
      DB_PASSWORD: secret
      DB_DATABASE: users
      SECRET_KEY: "l1jp*8SggVjlWpGI5QkFG3UUB&ob@lY@s4v^h83&Rv7YjI4yD8FqENTr^6ju40Cz"
    ports:
      - "4000:4000"

  users-db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: secret
