version: "2.1"
services:
  users:
    build: .
    environment:
      DB_HOSTNAME: users-db
      DB_USERNAME: users
      DB_PASSWORD: secret
      DB_DATABASE: users
    ports:
      - "4000:4000"

  users-db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: secret
